# Generated by Django 2.2 on 2019-10-19 22:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0016_auto_20190924_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Reportes/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
