# Generated by Django 2.2 on 2019-10-24 00:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0018_auto_20191019_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('AA', 'Añadir adquisición'), ('AR', 'Añadir renta'), ('EA', 'Editar adquisición'), ('ER', 'Editar renta'), ('PA', 'Post adquisición'), ('PR', 'Post renta'), ('RA', 'Respuesta adquisición'), ('RR', 'Respuesta renta')], max_length=2)),
                ('id_property', models.PositiveIntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_status', models.BooleanField(default=False)),
                ('user_receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Receptor', to='propiedades2.Staff')),
                ('user_transmitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Transmisor', to='propiedades2.Staff')),
            ],
        ),
    ]
