# Generated by Django 2.2 on 2019-10-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0019_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type_property',
            field=models.CharField(choices=[('AA', 'Añadir adquisición'), ('AR', 'Añadir renta'), ('EA', 'Editar adquisición'), ('ER', 'Editar renta'), ('PA', 'Post adquisición'), ('PR', 'Post renta'), ('RA', 'Respuesta adquisición'), ('RR', 'Respuesta renta')], default=None, max_length=2),
            preserve_default=False,
        ),
    ]
