# Generated by Django 2.2 on 2019-05-09 01:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role_number', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Fotos/')),
                ('property_use', models.CharField(choices=[('IGL', 'Iglesia'), ('GRU', 'Grupo'), ('COL', 'Colegio'), ('HAB', 'Habitacional'), ('Otro', 'Otro')], max_length=5)),
                ('acquisition_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('writing_data', models.CharField(choices=[('COM', 'Compraventa'), ('DON', 'Donación'), ('SUB', 'Subdivisión'), ('Otro', 'Otro')], max_length=5)),
                ('number_AASI', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.FileField(blank=True, upload_to='Documentos/')),
                ('publish_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('TC', 'Tipo contrato'), ('ES', 'Escritura'), ('CD', 'Certificado de dominio'), ('PR', 'Prohibiciones'), ('SE', 'Expropiación SERVIU'), ('OT', 'Otro'), ('EM', 'Expropiación Municipalidad'), ('CP', 'CIP'), ('NC', 'Número certificado'), ('PL', 'Planos'), ('PE', 'Permiso de edificación'), ('RM', 'Recepción municipal'), ('CA', 'Certificado avalúo'), ('CD', 'Certificado no deuda')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('number', models.PositiveIntegerField()),
                ('commune', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('RM', 'Region Metropolitana'), ('TP', 'Region de Tarapaca'), ('AF', 'Region de Antofagasta'), ('CQ', 'Region de Coquimbo'), ('VP', 'Region de Valparaiso'), ('BO', "Region de O'Higgins"), ('ML', 'Region del Maule'), ('CP', 'Region de Concepcion'), ('AR', 'Region de la Araucania'), ('LG', 'Region de los lagos'), ('AS', 'Region de Aysen'), ('MG', 'Region de Magallanes'), ('RS', 'Region de los Rios'), ('AP', 'Region de Arica y Parinacota'), ('ÑB', 'Region del Ñuble')], max_length=200)),
                ('lot_number', models.PositiveIntegerField(blank=True, null=True)),
                ('plot', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiiRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destiny', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_appraisal', models.PositiveIntegerField(blank=True, null=True)),
                ('owner_name_SII', models.CharField(blank=True, max_length=100, null=True)),
                ('total_debt', models.PositiveIntegerField(blank=True, null=True)),
                ('ex_contributions', models.BooleanField(default=False)),
                ('appraisal_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CerAvaluo', to='propiedades2.Document')),
                ('debt_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CerNoDeuda', to='propiedades2.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role_number', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Fotos/')),
                ('property_use', models.CharField(choices=[('IGL', 'Iglesia'), ('GRU', 'Grupo'), ('COL', 'Colegio'), ('HAB', 'Habitacional'), ('Otro', 'Otro')], max_length=100)),
                ('ground_surface', models.CharField(blank=True, max_length=100, null=True)),
                ('square_m_build', models.CharField(blank=True, max_length=100, null=True)),
                ('e_construction_m', models.CharField(blank=True, max_length=100, null=True)),
                ('municipal_n', models.PositiveIntegerField(blank=True, null=True)),
                ('n_building_permit', models.PositiveIntegerField(blank=True, null=True)),
                ('value_land', models.CharField(blank=True, max_length=100, null=True)),
                ('value_construction', models.CharField(blank=True, max_length=100, null=True)),
                ('acquiring_name', models.CharField(max_length=100)),
                ('supplier_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.PositiveIntegerField()),
                ('contract_type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TipoContratoArriendo', to='propiedades2.Document')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='propiedades2.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('acquisition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='PostAcquisition', to='propiedades2.Acquisition')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Auth_users.UserProfile')),
                ('rent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='PostRent', to='propiedades2.Rent')),
            ],
        ),
        migrations.CreateModel(
            name='NotaryAcquisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notary', models.CharField(blank=True, max_length=100, null=True)),
                ('writing_year', models.PositiveIntegerField(blank=True, null=True)),
                ('sale_price', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_title', models.CharField(blank=True, max_length=100, null=True)),
                ('current_title', models.CharField(blank=True, max_length=100, null=True)),
                ('domain_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CertificadoDominio', to='propiedades2.Document')),
                ('expropriation_serviu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Serviu', to='propiedades2.Document')),
                ('prohibitions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Prohibiciones', to='propiedades2.Document')),
                ('writing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Escritura', to='propiedades2.Document')),
            ],
        ),
        migrations.CreateModel(
            name='InternalAccountantsAcq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_land', models.CharField(blank=True, max_length=100, null=True)),
                ('value_construction', models.CharField(blank=True, max_length=100, null=True)),
                ('acquiring_name', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TipoContratoAdquisicion', to='propiedades2.Document')),
                ('others', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Otros', to='propiedades2.Document')),
            ],
        ),
        migrations.CreateModel(
            name='ArchitectureRecordAcq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground_surface', models.CharField(blank=True, max_length=100, null=True)),
                ('square_m_build', models.CharField(blank=True, max_length=100, null=True)),
                ('e_construction_m', models.CharField(blank=True, max_length=100, null=True)),
                ('municipal_n', models.PositiveIntegerField(blank=True, null=True)),
                ('n_building_permit', models.PositiveIntegerField(blank=True, null=True)),
                ('blueprints', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Planos', to='propiedades2.Document')),
                ('building_permit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PerEdificacion', to='propiedades2.Document')),
                ('certified_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NumCertificado', to='propiedades2.Document')),
                ('cip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cip', to='propiedades2.Document')),
                ('expropriation_mun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExMunicipalidad', to='propiedades2.Document')),
                ('municipal_reception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RecMunicipal', to='propiedades2.Document')),
            ],
        ),
        migrations.AddField(
            model_name='acquisition',
            name='SII',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SII_acq', to='propiedades2.SiiRecord'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='arquitecture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquitecture_acq', to='propiedades2.ArchitectureRecordAcq'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='internal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_acq', to='propiedades2.InternalAccountantsAcq'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='propiedades2.Location'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='notary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notary_acq', to='propiedades2.NotaryAcquisition'),
        ),
    ]
