# Generated by Django 2.2 on 2019-04-30 02:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='acquisition_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
