# Generated by Django 2.2.2 on 2019-06-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0003_auto_20190624_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttypec',
            name='type',
            field=models.CharField(choices=[('TC', 'Tipo contrato'), ('ES', 'Escritura'), ('DC', 'Certificado de dominio'), ('PR', 'Prohibiciones'), ('SE', 'Expropiación SERVIU'), ('OT', 'Otro'), ('EM', 'Expropiación Municipalidad'), ('CP', 'CIP'), ('NC', 'Número certificado'), ('PL', 'Planos'), ('PE', 'Permiso de edificación'), ('RM', 'Recepción municipal'), ('CA', 'Certificado avalúo'), ('CD', 'Certificado no deuda')], default='TC', max_length=5),
        ),
    ]
