# Generated by Django 2.2.2 on 2019-06-24 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0004_auto_20190624_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
    ]
