# Generated by Django 2.2.2 on 2019-06-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0006_staff_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='first_name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
