# Generated by Django 2.2.2 on 2019-08-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0008_auto_20190820_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region_choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronimo', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
