# Generated by Django 2.2.2 on 2019-08-22 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0009_region_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronimo', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Region_choice',
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedades2.Region'),
        ),
    ]
