# Generated by Django 2.2.2 on 2019-08-22 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades2', '0010_auto_20190822_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='acronimo',
            new_name='acronym',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='nombre',
            new_name='name',
        ),
    ]
