# Generated by Django 2.0.4 on 2019-04-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
