# Generated by Django 2.0.4 on 2019-04-17 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_users', '0002_userprofile_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
    ]
