# Generated by Django 2.0.4 on 2019-04-17 20:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth_users', '0003_auto_20190416_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.FileField(blank=True, null=True, upload_to='Documentos/')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('number', models.PositiveIntegerField()),
                ('commune', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('RM', 'Region Metropolitana'), ('TP', 'Region de Tarapaca'), ('AF', 'Region de Antofagasta'), ('CQ', 'Region de Coquimbo'), ('VP', 'Region de Valparaiso'), ('BO', "Region de O'Higgins"), ('ML', 'Region del Maule'), ('CP', 'Region de Concepcion'), ('AR', 'Region de la Araucania'), ('LG', 'Region de los lagos'), ('AS', 'Region de Aysen'), ('MG', 'Region de Magallanes'), ('RS', 'Region de los Rios'), ('AP', 'Region de Arica y Parinacota'), ('ÑB', 'Region del Ñuble')], max_length=200)),
                ('lot_number', models.PositiveIntegerField(blank=True, null=True)),
                ('plot', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Auth_users.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role_number', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Fotos/')),
                ('property_use', models.CharField(choices=[('IGL', 'Iglesia'), ('GRU', 'Grupo'), ('COL', 'Colegio'), ('HAB', 'Habitacional'), ('Otro', 'Otro')], max_length=100)),
                ('ground_surface', models.CharField(blank=True, max_length=100, null=True)),
                ('square_m_build', models.CharField(blank=True, max_length=100, null=True)),
                ('e_construction_m', models.CharField(blank=True, max_length=100, null=True)),
                ('municipal_n', models.PositiveIntegerField(blank=True, null=True)),
                ('n_building_permit', models.PositiveIntegerField(blank=True, null=True)),
                ('value_land', models.CharField(blank=True, max_length=100, null=True)),
                ('value_construction', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Propiedades.Property')),
                ('number_AASI', models.PositiveIntegerField(blank=True, null=True)),
                ('acquisition_date', models.DateField(default=django.utils.timezone.now)),
                ('acquiring_name', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('notary', models.CharField(blank=True, max_length=100, null=True)),
                ('writing_year', models.PositiveIntegerField(blank=True, null=True)),
                ('sale_price', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_title', models.CharField(blank=True, max_length=100, null=True)),
                ('current_title', models.CharField(blank=True, max_length=100, null=True)),
                ('destiny', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_appraisal', models.PositiveIntegerField(blank=True, null=True)),
                ('owner_name_SII', models.CharField(blank=True, max_length=100, null=True)),
                ('total_debt', models.PositiveIntegerField(blank=True, null=True)),
                ('ex_contributions', models.NullBooleanField()),
                ('appraisal_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CerAvaluo', to='Propiedades.Document')),
                ('blueprints', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Planos', to='Propiedades.Document')),
                ('building_permit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PerEdificacion', to='Propiedades.Document')),
                ('certified_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NumCertificado', to='Propiedades.Document')),
                ('cip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cip', to='Propiedades.Document')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TipoContratoAdquisicion', to='Propiedades.Document')),
                ('debt_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CerNoDeuda', to='Propiedades.Document')),
                ('domain_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CertificadoDominio', to='Propiedades.Document')),
                ('expropriation_mun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExMunicipalidad', to='Propiedades.Document')),
                ('expropriation_serviu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Serviu', to='Propiedades.Document')),
                ('municipal_reception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RecMunicipal', to='Propiedades.Document')),
                ('others', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Otros', to='Propiedades.Document')),
                ('prohibitions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Prohibiciones', to='Propiedades.Document')),
                ('writing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Escritura', to='Propiedades.Document')),
            ],
            bases=('Propiedades.property',),
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Propiedades.Property')),
                ('acquiring_name', models.CharField(max_length=100)),
                ('supplier_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.PositiveIntegerField()),
                ('contract_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='TipoContratoArriendo', to='Propiedades.Document')),
            ],
            bases=('Propiedades.property',),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Propiedades.Location'),
        ),
        migrations.AddField(
            model_name='post',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='PostPropiedad', to='Propiedades.Property'),
        ),
    ]
