# Generated by Django 2.1.1 on 2019-04-08 22:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_AASI', models.PositiveIntegerField()),
                ('acquisition_date', models.DateField()),
                ('acquiring_name', models.CharField(max_length=100)),
                ('supplier_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.PositiveIntegerField()),
                ('notary', models.CharField(max_length=100)),
                ('writing_year', models.PositiveIntegerField()),
                ('sale_price', models.CharField(max_length=100)),
                ('previous_title', models.CharField(max_length=100)),
                ('current_title', models.CharField(max_length=100)),
                ('destiny', models.CharField(max_length=100)),
                ('tax_appraisal', models.PositiveIntegerField()),
                ('owner_name_SII', models.CharField(max_length=100)),
                ('total_debt', models.PositiveIntegerField()),
                ('ex_contributions', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Doc_property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.FileField(blank=True, null=True, upload_to='Documentos/')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('number', models.PositiveIntegerField()),
                ('commune', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('RM', 'Region Metropolitana'), ('TP', 'Region de Tarapaca'), ('AF', 'Region de Antofagasta'), ('CQ', 'Region de Coquimbo'), ('VP', 'Region de Valparaiso'), ('BO', 'Region de OHiggins'), ('ML', 'Region del Maule'), ('CP', 'Region de Concepcion'), ('AR', 'Region de la Araucania'), ('LG', 'Region de los lagos'), ('AS', 'Region de Aysen'), ('MG', 'Region de Magallanes'), ('RS', 'Region de los Rios'), ('AP', 'Region de Arica y Parinacota'), ('ÑB', 'Region del Ñuble')], max_length=200)),
                ('lot_number', models.PositiveIntegerField(blank=True)),
                ('plot', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Auth_users.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Post_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Propiedades.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role_number', models.PositiveIntegerField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='Fotos/')),
                ('property_use', models.CharField(choices=[('IGL', 'Iglesia'), ('GRU', 'Grupo'), ('COL', 'Colegio'), ('HAB', 'Habitacional'), ('Otro', 'Otro')], max_length=2)),
                ('ground_surface', models.CharField(max_length=100)),
                ('square_m_build', models.CharField(max_length=100)),
                ('e_construction_m', models.CharField(max_length=100)),
                ('municipal_n', models.PositiveIntegerField()),
                ('n_building_permit', models.PositiveIntegerField()),
                ('value_land', models.CharField(max_length=100)),
                ('value_construction', models.CharField(max_length=100)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Propiedades.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquiring_name', models.CharField(max_length=100)),
                ('supplier_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.PositiveIntegerField()),
                ('contract_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='TipoContratoArriendo', to='Propiedades.Doc_property')),
            ],
        ),
        migrations.AddField(
            model_name='doc_property',
            name='doc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Propiedades.Document'),
        ),
        migrations.AddField(
            model_name='doc_property',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Propiedad', to='Propiedades.Property'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='appraisal_certificate',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='CerAvaluo', to='Propiedades.Doc_property'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='blueprints',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Planos', to='Propiedades.Doc_property'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='building_permit',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='PerEdificacion', to='Propiedades.Doc_property'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='certified_number',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='NumCertificado', to='Propiedades.Doc_property'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='cip',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cip', to='Propiedades.Doc_property'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='contract_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='TipoContratoAdquisicion', to='Propiedades.Doc_property'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='debt_certificate',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='CerNoDeuda', to='Propiedades.Doc_property'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='domain_certificate',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='CertificadoDominio', to='Propiedades.Doc_property'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='expropriation_mun',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExMunicipalidad', to='Propiedades.Doc_property'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='expropriation_serviu',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Serviu', to='Propiedades.Doc_property'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='municipal_reception',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='RecMunicipal', to='Propiedades.Doc_property'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='others',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Otros', to='Propiedades.Doc_property'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='prohibitions',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Prohibiciones', to='Propiedades.Doc_property'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='writing',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Escritura', to='Propiedades.Doc_property'),
        ),
    ]
