# Generated by Django 2.1.1 on 2019-04-08 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_user',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='property',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Propiedades.Property'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Post_user',
        ),
    ]
