# Generated by Django 2.1.1 on 2019-04-08 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0002_auto_20190408_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_property',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocPropiedad', to='Propiedades.Property'),
        ),
        migrations.AlterField(
            model_name='post',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='PostPropiedad', to='Propiedades.Property'),
        ),
    ]
