# Generated by Django 2.0.4 on 2019-04-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0003_auto_20190408_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('work_station', models.CharField(max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(choices=[('RM', 'Region Metropolitana'), ('TP', 'Region de Tarapaca'), ('AF', 'Region de Antofagasta'), ('CQ', 'Region de Coquimbo'), ('VP', 'Region de Valparaiso'), ('BO', "Region de O'Higgins"), ('ML', 'Region del Maule'), ('CP', 'Region de Concepcion'), ('AR', 'Region de la Araucania'), ('LG', 'Region de los lagos'), ('AS', 'Region de Aysen'), ('MG', 'Region de Magallanes'), ('RS', 'Region de los Rios'), ('AP', 'Region de Arica y Parinacota'), ('ÑB', 'Region del Ñuble')], max_length=200),
        ),
    ]
