# Generated by Django 2.0.4 on 2019-04-15 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0004_auto_20190415_2206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
