# Generated by Django 2.0.4 on 2019-04-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0005_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lot_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='plot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
