# Generated by Django 2.0.4 on 2019-04-17 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0009_administrator_digitizer_leadership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='digitizer',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='leadership',
            old_name='user',
            new_name='username',
        ),
    ]
