# Generated by Django 2.0.4 on 2019-04-17 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0010_auto_20190416_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='digitizer',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='leadership',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user_type',
            old_name='userprofile',
            new_name='user',
        ),
    ]
