# Generated by Django 2.0.4 on 2019-04-17 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0011_auto_20190416_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadership',
            old_name='user',
            new_name='username',
        ),
    ]
