# Generated by Django 2.0.4 on 2019-04-17 18:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0012_auto_20190416_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='digitizer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='doc_property',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='doc_property',
            name='prop',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user_type',
            name='user',
        ),
        migrations.RemoveField(
            model_name='acquisition',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='acquisition',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='acquisition',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='id',
        ),
        migrations.AddField(
            model_name='acquisition',
            name='property_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Propiedades.Property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='property_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Propiedades.Property'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='acquiring_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='acquisition_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='appraisal_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CerAvaluo', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='blueprints',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Planos', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='building_permit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PerEdificacion', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='certified_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NumCertificado', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='cip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cip', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='contract_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TipoContratoAdquisicion', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='current_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='debt_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CerNoDeuda', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='destiny',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='domain_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CertificadoDominio', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='ex_contributions',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='expropriation_mun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExMunicipalidad', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='expropriation_serviu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Serviu', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='municipal_reception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RecMunicipal', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='notary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='number_AASI',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='others',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Otros', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='owner_name_SII',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='previous_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='prohibitions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Prohibiciones', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='sale_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='tax_appraisal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='total_debt',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='writing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Escritura', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='writing_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='e_construction_m',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='ground_surface',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Fotos/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='municipal_n',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='n_building_permit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_use',
            field=models.CharField(choices=[('IGL', 'Iglesia'), ('GRU', 'Grupo'), ('COL', 'Colegio'), ('HAB', 'Habitacional'), ('Otro', 'Otro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='role_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='square_m_build',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='value_construction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='value_land',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='contract_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='TipoContratoArriendo', to='Propiedades.Document'),
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='digitizer',
        ),
        migrations.DeleteModel(
            name='Doc_property',
        ),
        migrations.DeleteModel(
            name='Leadership',
        ),
        migrations.DeleteModel(
            name='User_type',
        ),
    ]
