# Generated by Django 2.2 on 2019-04-25 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0013_auto_20190417_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acquisition',
            name='start_date',
        ),
        migrations.AddField(
            model_name='acquisition',
            name='writing_data',
            field=models.CharField(choices=[('Com', 'Compraventa'), ('Don', 'Donación'), ('Sub', 'Subdivisión'), ('Otro', 'Otro')], default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='appraisal_certificate',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='CerAvaluo', to='Propiedades.Document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='blueprints',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Planos', to='Propiedades.Document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='building_permit',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='PerEdificacion', to='Propiedades.Document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='certified_number',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='NumCertificado', to='Propiedades.Document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='cip',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Cip', to='Propiedades.Document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='debt_certificate',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='CerNoDeuda', to='Propiedades.Document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='domain_certificate',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='CertificadoDominio', to='Propiedades.Document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='expropriation_mun',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ExMunicipalidad', to='Propiedades.Document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='expropriation_serviu',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Serviu', to='Propiedades.Document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='municipal_reception',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='RecMunicipal', to='Propiedades.Document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='others',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Otros', to='Propiedades.Document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='prohibitions',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Prohibiciones', to='Propiedades.Document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='writing',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Escritura', to='Propiedades.Document'),
            preserve_default=False,
        ),
    ]
