# Generated by Django 2.2 on 2019-04-24 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0013_auto_20190417_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='cip',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Cip', to='Propiedades.Document'),
            preserve_default=False,
        ),
    ]
