# Generated by Django 2.2 on 2019-04-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0014_auto_20190424_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='writing_data',
            field=models.CharField(choices=[('COM', 'Compraventa'), ('DON', 'Donación'), ('SUB', 'Subdivisión'), ('Otro', 'Otro')], max_length=100),
        ),
    ]
