# Generated by Django 2.2 on 2019-04-25 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0015_auto_20190424_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acquisition',
            name='property_ptr',
        ),
        migrations.RemoveField(
            model_name='post',
            name='property',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='property_ptr',
        ),
        migrations.AddField(
            model_name='acquisition',
            name='e_construction_m',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='ground_surface',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acquisition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Fotos/'),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='location',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Propiedades.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acquisition',
            name='municipal_n',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='n_building_permit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acquisition',
            name='property_use',
            field=models.CharField(choices=[('IGL', 'Iglesia'), ('GRU', 'Grupo'), ('COL', 'Colegio'), ('HAB', 'Habitacional'), ('Otro', 'Otro')], default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acquisition',
            name='role_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='square_m_build',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='value_construction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='value_land',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='acquisition',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='PostAcquisition', to='Propiedades.Acquisition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='rent',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='PostRent', to='Propiedades.Rent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='e_construction_m',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='ground_surface',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Fotos/'),
        ),
        migrations.AddField(
            model_name='rent',
            name='location',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Propiedades.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='municipal_n',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='n_building_permit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='property_use',
            field=models.CharField(choices=[('IGL', 'Iglesia'), ('GRU', 'Grupo'), ('COL', 'Colegio'), ('HAB', 'Habitacional'), ('Otro', 'Otro')], default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='role_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='square_m_build',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='value_construction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='value_land',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='appraisal_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CerAvaluo', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='blueprints',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Planos', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='building_permit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PerEdificacion', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='certified_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NumCertificado', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='cip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cip', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='debt_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CerNoDeuda', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='domain_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CertificadoDominio', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='expropriation_mun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExMunicipalidad', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='expropriation_serviu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Serviu', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='municipal_reception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RecMunicipal', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='others',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Otros', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='prohibitions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Prohibiciones', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='writing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Escritura', to='Propiedades.Document'),
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
