# Generated by Django 2.2 on 2019-04-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0016_auto_20190425_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('es', 'escritura')], default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='comment',
            field=models.TextField(),
        ),
    ]
