# Generated by Django 2.2 on 2019-04-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0017_auto_20190426_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('es', 'escritura')], default='es', max_length=2),
        ),
    ]
