# Generated by Django 2.2 on 2019-04-25 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0017_auto_20190424_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='appraisal_certificate',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='CerAvaluo', to='Propiedades.Document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='blueprints',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Planos', to='Propiedades.Document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='building_permit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PerEdificacion', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='cip',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cip', to='Propiedades.Document'),
        ),
    ]
