# Generated by Django 2.2 on 2019-04-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0018_auto_20190426_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('es', 'escritura')], max_length=2),
        ),
    ]
