# Generated by Django 2.2 on 2019-04-25 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0018_auto_20190424_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='appraisal_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CerAvaluo', to='Propiedades.Document'),
        ),
    ]
