# Generated by Django 2.2 on 2019-04-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0019_auto_20190426_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('ES', 'Escritura'), ('CD', 'Certificado de dominio'), ('PR', 'Prohibiciones'), ('SE', 'Expropiación SERVIU'), ('OT', 'Otro'), ('EM', 'Expropiación Municipalidad'), ('CP', 'CIP'), ('NC', 'Número certificado'), ('PL', 'Planos'), ('PE', 'Permiso de edificación'), ('RM', 'Recepción municipal'), ('CA', 'Certificado avalúo'), ('CD', 'Certificado no deuda')], max_length=2),
        ),
    ]
