# Generated by Django 2.2 on 2019-04-25 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0020_auto_20190424_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='certified_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NumCertificado', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='cip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cip', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='debt_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CerNoDeuda', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='domain_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CertificadoDominio', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='expropriation_mun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ExMunicipalidad', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='expropriation_serviu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Serviu', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='municipal_reception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RecMunicipal', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='others',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Otros', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='prohibitions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Prohibiciones', to='Propiedades.Document'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='writing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Escritura', to='Propiedades.Document'),
        ),
    ]
