# Generated by Django 2.2 on 2019-04-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0020_auto_20190427_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='ex_contributions',
            field=models.BooleanField(default=False),
        ),
    ]
