# Generated by Django 2.2 on 2019-04-25 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0021_auto_20190424_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acquisition',
            name='start_date',
        ),
    ]
